[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[build]]
  command = "npm run build"
  publish = "build/"
  [[build.environment]]
    NODE_ENV = "production"
  [build.headers]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=31536000, immutable"
